#Mateo Martínez Sanz
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Sun May 22 11:58:27 2022
#
import wx
from wx import adv


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

def Probarint(elemento):
        try:
            int(elemento)
            return True
        except:
            return False
def Listadeniveles():
    listadeniveles = []
    with open("D:/01 Estadistica/1/Cuatrimestre2/PAR/Practica/Proyecto2/niveles.txt","r")as archivo:
        numerodeniveles=int(archivo.readline())
        a=0
        for elemento in archivo:
            elemento=elemento.rstrip('\n')
            if Probarint(elemento):
                listadeniveles.append(int(a+1))
            a+=1
    return listadeniveles
def Records():
    with open('D:/01 Estadistica/1/Cuatrimestre2/PAR/Practica/Proyecto2/records.txt')as archivo:
        records=archivo.read().split()
    return records
def crearnivel(nivel,listadeniveles):
    listadecoches=[]
    with open("D:/01 Estadistica/1/Cuatrimestre2/PAR/Practica/Proyecto2/niveles.txt","r")as archivo:
        numerodelinea=listadeniveles[nivel-1]
        archivo=archivo.readlines()
        numerrodecoches=int(archivo[numerodelinea])
        for a in range(numerrodecoches):
            elemento=str(archivo[numerodelinea+a+1].rstrip('\n'))
            listadecoches.append(elemento)
    return listadecoches


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((660, 525))
        self.SetTitle("Par-King")
        self.contador = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.Contador, self.contador)
        self.listadeniveles = Listadeniveles()
        self.records = Records()
        self.nivel = -1
        opcionesdenivel = []
        for a in range(len(self.records)):
            opcionesdenivel.append("Nivel " + str(a+1) + " / " + str(self.records[a]))
        opcionesdenivel.append("Nivel " + str(len(self.records)+1) + " / --")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Seleccione un nivel", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.label_3.SetMinSize((500, 50))

        self.label_3.SetFont(wx.Font(28, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_1.Add(self.label_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 0, wx.RIGHT, 10)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Niveles")
        sizer_4.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.list_box_1 = wx.ListBox(self.panel_1, wx.ID_ANY, choices=opcionesdenivel)
        self.list_box_1.SetMinSize((100, 385))
        self.Bind(wx.EVT_LISTBOX, self.Elegirnivel, self.list_box_1)
        sizer_4.Add(self.list_box_1, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_2.SetMinSize((400, 400))
        sizer_2.Add(self.panel_2, 0, 0, 0)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_5, 0, wx.EXPAND | wx.LEFT, 10)

        self.label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "--", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.label_2.SetMinSize((100, 100))
        self.label_2.SetFont(wx.Font(50, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_5.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "Jugar")
        self.Bind(wx.EVT_BUTTON, self.Jugar, self.button_1)
        self.button_1.Enable(False)
        sizer_5.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Deshacer")
        sizer_5.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.Bind(wx.EVT_BUTTON, self.Deshacer, self.button_2)
        self.button_2.Enable(False)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

    def Elegirnivel(self, event):   #Elige el nivel en funcion de la seleccion de la list_box y pone los coches en el panel, si habia ates, los destruye
                                    #Tambien activa el boton de jugar
        self.label_2.SetLabel("--")
        if self.nivel != -1:
            self.panel_2.DestroyChildren()
        for a in range(8):
            muro = wx.Panel(self.panel_2, wx.ID_ANY)
            muro.SetBackgroundColour(wx.Colour(0,0,0))
            muro.SetSize(50,50)
            muro.SetPosition((a*50,0))
        for a in range(1,7):
            for b in range(2):
                if a !=3 or b !=1:
                    muro = wx.Panel(self.panel_2, wx.ID_ANY)
                    muro.SetBackgroundColour(wx.Colour(0,0,0))
                    muro.SetSize(50,50)
                    muro.SetPosition((350*b,a*50))
        for a in range(8):
            muro = wx.Panel(self.panel_2, wx.ID_ANY)
            muro.SetBackgroundColour(wx.Colour(0,0,0))
            muro.SetSize(50,50)
            muro.SetPosition((a*50,350))
        self.nivel = int(self.list_box_1.GetSelection())
        listadecoches = crearnivel(self.nivel+1, self.listadeniveles)
        a=0
        colores = [wx.Colour(255, 0, 0), wx.Colour(0, 255, 0), wx.Colour(0, 0, 255), wx.Colour(255, 255, 0), wx.Colour(255, 0, 255), wx.Colour(0, 255, 255), wx.Colour(255, 255, 255), wx.Colour(255, 128, 0), wx.Colour(128, 0, 0), wx.Colour(0, 128, 0), wx.Colour(0, 0, 128), wx.Colour(128, 128, 0), wx.Colour(128, 0, 128), wx.Colour(0, 128, 128), wx.Colour(128, 128, 128)]
        for elemento in listadecoches:
            coche = wx.Button(self.panel_2, id  = (100+a))
            coche.Enable(False)
            coche.SetBackgroundColour(colores[a])
            if elemento[0] == 'H':
                coche.SetPosition((50*int(elemento[1]), 50*int(elemento[2])))
                coche.SetFont(wx.Font(50, wx.FONTFAMILY_SCRIPT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0))
                coche.SetLabel('|')
                coche.SetSize(50*int(elemento[3]), 50)
            else:
                coche.SetPosition((50*int(elemento[1]), 50*int(elemento[2])))
                coche.SetFont(wx.Font(50, wx.FONTFAMILY_SCRIPT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0))
                coche.SetLabel('─')
                coche.SetSize(50, 50*int(elemento[3]))
            coche.Bind(wx.EVT_BUTTON, self.Mover, coche)
            a+=1
        self.label_3.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.label_3.SetLabel("Nivel "+str(self.nivel+1) + "\nPulse jugar para empezar")
        self.button_1.Enable(True)

    def Mover(self, event):     #Comprueba que el coche se puede mover, si es asi se mueve, si no hace el sonido e indica que no se puede mover
        coche = event.GetEventObject()
        posible = True
        if coche.GetSize()[1] == 50:
            if wx.GetMousePosition()[0] - self.GetScreenPosition()[0] - 128 > coche.GetPosition()[0] + coche.GetSize()[0]/2:
                posicion = (coche.GetPosition()[0] + 50, coche.GetPosition()[1])
                for elemento in self.panel_2.GetChildren():
                    if elemento.GetSize()[1] == 50:
                        if elemento.GetPosition()[1] == posicion[1]:
                            if elemento.GetPosition()[0] < posicion[0] + coche.GetSize()[0] and elemento.GetPosition()[0] > coche.GetPosition()[0]:
                                posible = False
                                break
                    else:
                        for a in range(elemento.GetPosition()[1], elemento.GetPosition()[1] + elemento.GetSize()[1]):
                            if a == posicion[1]:
                                if elemento.GetPosition()[0] < posicion[0] + coche.GetSize()[0] and elemento.GetPosition()[0] > coche.GetPosition()[0]:
                                    posible = False
                                    break
            else:
                posicion = (coche.GetPosition()[0] - 50, coche.GetPosition()[1])
                for elemento in self.panel_2.GetChildren():
                    if elemento.GetSize()[1] == 50:
                        if elemento.GetPosition()[1] == posicion[1]:
                            if elemento.GetPosition()[0] + elemento.GetSize()[0] - 1 > posicion[0] and elemento.GetPosition()[0] < coche.GetPosition()[0]:
                                posible = False
                                break
                    else:
                        for a in range(elemento.GetPosition()[1], int(elemento.GetPosition()[1] + elemento.GetSize()[1]), 50) :
                            if a == posicion[1]:
                                if elemento.GetPosition()[0] + elemento.GetSize()[0] - 1 > posicion[0] and elemento.GetPosition()[0] < coche.GetPosition()[0]:
                                    posible = False
                                    break
        else:
            if wx.GetMousePosition()[1] - self.GetScreenPosition()[1] - 101 > coche.GetPosition()[1] + coche.GetSize()[1]/2:
                posicion = (coche.GetPosition()[0], coche.GetPosition()[1] + 50)
                for elemento in self.panel_2.GetChildren():
                    if elemento.GetSize()[0] == 50:
                        if elemento.GetPosition()[0] == posicion[0]:
                            if elemento.GetPosition()[1] < posicion[1] + coche.GetSize()[1] and elemento.GetPosition()[1] > coche.GetPosition()[1]:
                                posible = False
                                break
                    else:
                        for a in range(elemento.GetPosition()[0], elemento.GetPosition()[0] + elemento.GetSize()[0]):
                            if a == posicion[0]:
                                if elemento.GetPosition()[1] < posicion[1] + coche.GetSize()[1] and elemento.GetPosition()[1] > coche.GetPosition()[1]:
                                    posible = False
                                    break
            else:
                posicion = (coche.GetPosition()[0], coche.GetPosition()[1] - 50)
                for elemento in self.panel_2.GetChildren():
                    if elemento.GetSize()[0] == 50:
                        if elemento.GetPosition()[0] == posicion[0]:
                            if elemento.GetPosition()[1] + elemento.GetSize()[1] - 1 > posicion[1] and elemento.GetPosition()[1] < coche.GetPosition()[1]:
                                posible = False
                                break
                    else:
                        for a in range(elemento.GetPosition()[0], int(elemento.GetPosition()[0] + elemento.GetSize()[0]), 50) :
                            if a == posicion[0]:
                                if elemento.GetPosition()[1] + elemento.GetSize()[1] - 1 > posicion[1] and elemento.GetPosition()[1] < coche.GetPosition()[1]:
                                    posible = False
                                    break
        if posible == True:
            self.label_3.SetFont(wx.Font(28, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
            self.label_3.SetLabel('Nivel '+str(self.nivel+1))
            self.deshacer.append([coche.GetPosition(), coche.GetId()])
            coche.SetPosition(posicion)
            self.button_2.Enable(True)
            if posicion == (300,150) and coche.GetId() == 100:  #Se completa el nivel
                self.contador.Stop()
                for elemento in self.panel_2.GetChildren():
                    elemento.Enable(False)
                self.button_2.Enable(False)
                self.list_box_1.Enable(True)
                self.label_3.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
                self.label_3.SetLabel('¡Felicidades!,\nselecciona un nivel para continuar')
                opcionesdenivel = []
                datosderecords=""
                nivelmaximo = len(self.records)
                with open("D:/01 Estadistica/1/Cuatrimestre2/PAR/Practica/Proyecto2/records.txt", "r")as archivo:
                    records=archivo.readline().split()
                if nivelmaximo==self.nivel:
                    records.append(self.contar)
                    nivelmaximo+=1
                else:
                    if int(records[self.nivel])<self.contar:
                        records[self.nivel]=str(self.contar)
                for a in range(len(records)):
                    datosderecords+=str(records[a])+" "
                with open("records.txt","w")as archivo:
                    archivo.write(datosderecords)
                    archivo.truncate()
                for a in range(len(records)):
                    opcionesdenivel.append("Nivel " + str(a+1) + " / " + str(records[a]))
                opcionesdenivel.append("Nivel " + str(a+2) + " / --")
                self.list_box_1.Set(opcionesdenivel)
        else:
            self.label_3.SetFont(wx.Font(28, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
            wx.adv.Sound("hit.wav").Play()
            self.label_3.SetLabel('Movimiento imposible')

    def Deshacer(self, event):  #Deshace movimientos
        if len(self.deshacer) > 0:
            coche = self.panel_2.FindWindowById(self.deshacer[-1][1])
            coche.SetPosition(self.deshacer[-1][0])
            self.deshacer.pop()
            if len(self.deshacer) == 0:
                self.button_2.Enable(False)

    def Jugar(self, event):     #Activa los coches del nivel y actualiza el estado e otros objetos
        for elemento in self.panel_2.GetChildren():
            elemento.Enable(True)
        self.list_box_1.Enable(False)
        self.button_1.Enable(False)
        self.contar = 90
        self.label_2.SetLabel(str(self.contar))
        self.deshacer = []
        self.contador.Start(1000)

    def Contador(self, event): #Cuenta el tiempo que queda en el nivel
        self.contar -= 1
        self.label_2.SetLabel(str(self.contar))
        if self.contar == 0:    #Si es 0, se pierde
            self.contador.Stop()
            for elemento in self.panel_2.GetChildren():
                elemento.Enable(False)
            self.button_2.Enable(False)
            self.list_box_1.Enable(True)
            self.label_3.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
            self.label_3.SetLabel('Perdiste,\nselecciona un nivel para continuar')
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
